CREATE TABLE RELACIONAMENTO (
    ID             INTEGER NOT NULL,
    IDMUSICO1      INTEGER NOT NULL,
    IDMUSICO2      INTEGER NOT NULL,
    STATUS         VARCHAR(25) NOT NULL
);

ALTER TABLE RELACIONAMENTO ADD CONSTRAINT PK_RELACIONAMENTO PRIMARY KEY (ID);
ALTER TABLE RELACIONAMENTO ADD CONSTRAINT FK_RELACIONAMENTO_MUSICO1 FOREIGN KEY (IDMUSICO1) REFERENCES MUSICO;
ALTER TABLE RELACIONAMENTO ADD CONSTRAINT FK_RELACIONAMENTO_MUSICO2 FOREIGN KEY (IDMUSICO2) REFERENCES MUSICO;

CREATE SEQUENCE SEQ_RELACIONAMENTO START WITH 1 INCREMENT BY 1;