CREATE TABLE CURTIDA (
    ID                 INTEGER NOT NULL,
    IDMUSICO           INTEGER NOT NULL,
    IDPOST             INTEGER NOT NULL
);

CREATE UNIQUE INDEX curtida_idx ON CURTIDA (id);

ALTER TABLE CURTIDA ADD CONSTRAINT PK_CURTIDA PRIMARY KEY (ID);
ALTER TABLE CURTIDA ADD CONSTRAINT FK_CURTIDA_MUSICO FOREIGN KEY (IDMUSICO) REFERENCES MUSICO;
ALTER TABLE CURTIDA ADD CONSTRAINT FK_CURTIDA_POST FOREIGN KEY (IDPOST) REFERENCES POST;

CREATE SEQUENCE SEQ_CURTIDA START WITH 1 INCREMENT BY 1;