CREATE TABLE COMENTARIO (
    ID                 INTEGER NOT NULL,
    IDMUSICO           INTEGER NOT NULL,
    IDPOST             INTEGER NOT NULL,
    TEXTO              VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX comentario_idx ON COMENTARIO (id);

ALTER TABLE COMENTARIO ADD CONSTRAINT PK_COMENTARIO PRIMARY KEY (ID);
ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COMENTARIO_MUSICO FOREIGN KEY (IDMUSICO) REFERENCES MUSICO;
ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COMENTARIO_POST FOREIGN KEY (IDPOST) REFERENCES POST;

CREATE SEQUENCE SEQ_COMENTARIO START WITH 1 INCREMENT BY 1;